### ISSUE TITLE
Save Download progress like mega.nz, steam etc

### ISSUE THREAD

**Issue by Neyunse** [hgouveia/node-downloader-helper#63] opened 2021-08-22 00:56 UTC
I don't know if this would be easy to add, but it would be interesting if the download progress is stored if the browser or electron js is closed.

**Comment by Chaphasilor** [comment] 2021-08-22 18:32
This is a duplicate of #13 and could be fixed by #34 and #54 :)

**Comment by hgouveia** [comment] 2022-03-14 20:17
Implemented on v2.1.0

**Closed by hgouveia** 2022-03-14 20:17 UTC
Labels: duplicate
