### ISSUE TITLE
Download finishes before reaching 100%

### ISSUE THREAD

**Issue by kingio** [hgouveia/node-downloader-helper#11] opened 2019-03-14 11:49 UTC
When download reaches 2%, status goes to FINISHED and `end` event is fired.
Server has `accept-ranges: bytes`  and it's an nginx acting as CDN with Cloudflare layer over it.
Also it only happens over Windows. On linux it works fine.

I had to make this hack:
```js
let download = new DownloaderHelper(url, destination);
let lastStat

download.on('progress', stats => {
        console.log(stats.progress);
        lastStat = stats
    })
    .on('stateChanged', state => {
        if (state == "FINISHED") {
            console.log("status changed", lastStat);
            if (lastStat.progress === 100) {
                resolve()
            } else {
                download.resume()
            }
        }
    })
    .start()
```

That way it keeps going until reaches 100%.

**Comment by hgouveia** [comment] 2019-03-14 16:30
hello @kingio  is this url a public url that you could share , to be able to reproduce it?

**Comment by kingio** [comment] 2019-03-18 10:47
nope :(

**Comment by hgouveia** [comment] 2019-03-18 11:49
@kingio  if you are able to re-create the same environment with vagrant with minimal setup or something that i could use to reproduce it would be very helpful

**Comment by mass85** [comment] 2019-07-11 17:07
This problem is more general. When HTTP server is restarted, TCP connection is closed, readable and writeable streams are closed and transfer finished event is reported: https://github.com/hgouveia/node-downloader-helper/blob/6f2c5ce87592df405aa1db9fcd0285ded776938f/src/index.js#L200 Unfortunately it does not mean that whole file has been transferred. So I think that library should check if file has been really transferred by checking bytes count.

Similar behaviour I get when I use axios, that is why I think it is Node specific rather than a library problem.

**Comment by hgouveia** [comment] 2020-04-07 08:54
> This problem is more general. When HTTP server is restarted, TCP connection is closed, readable and writeable streams are closed and transfer finished event is reported:
> 
> https://github.com/hgouveia/node-downloader-helper/blob/6f2c5ce87592df405aa1db9fcd0285ded776938f/src/index.js#L200
> 
> Unfortunately it does not mean that whole file has been transferred. So I think that library should check if file has been really transferred by checking bytes count.
> Similar behaviour I get when I use axios, that is why I think it is Node specific rather than a library problem, but still it should be handled.

i've found out that increasing the timeout could help, ex: 
`const dl = new DownloadHelper(url, __dirname, { httpsRequestOptions: { timeout: (1000 * 60 * 60) * 3 } }` (3h)

not sure if will work in all situation

**Comment by OxCom** [comment] 2022-02-11 07:35
> The 'finish' event is emitted after the stream.end() method has been called, and all data has been flushed to the underlying system.
> see: https://nodejs.org/api/stream.html#event-finish

@hgouveia there are few issues that I know with streams on NodeJS (win/nix systems):
- pipe can stuck and do not receive the data at all. in this case we should implement timeout check the transferred data size during piping process
- before NodeJS 16 'finish' event sometimes can be missed, so we have to call 'close()' on stream by our own
- during download of the file we have to perform a check that file size is correct, because sometimes the transfer can be successful, but not all data has been transferred. here the check of file size should be done to cover incomplete successful download (btw there are reports for such cases in different libs, but without any solutions from devs and NodeJS sides)

**Comment by hgouveia** [comment] 2022-02-11 08:19
> > The 'finish' event is emitted after the stream.end() method has been called, and all data has been flushed to the underlying system.
> > see: https://nodejs.org/api/stream.html#event-finish
> 
> @hgouveia there are few issues that I know with streams on NodeJS (win/nix systems):
> 
> * pipe can stuck and do not receive the data at all. in this case we should implement timeout check the transferred data size during piping process
> * before NodeJS 16 'finish' event sometimes can be missed, so we have to call 'close()' on stream by our own
> * during download of the file we have to perform a check that file size is correct, because sometimes the transfer can be successful, but not all data has been transferred. here the check of file size should be done to cover incomplete successful download (btw there are reports for such cases in different libs, but without any solutions from devs and NodeJS sides)

@OxCom thanks! please feel free to contribute with a PR if you are able to, i will take a look into this suggestion as well

**Comment by beiguancyc** [comment] 2022-04-08 06:20
I met the same question and 

const dl = new DownloadHelper(url, __dirname, { httpsRequestOptions: { timeout: (1000 * 60 * 60) * 3 } }

is not work for me

**Comment by hgouveia** [comment] 2022-08-04 16:19
added new behavior in v2.1.2, that will resume the download if detect is incomplete

**Closed** 2022-08-04 16:20 UTC
Labels: bug
