### ISSUE TITLE
Keep the promise from the start when downloading paused and resume.

### ISSUE THREAD

**Issue by semdy** [hgouveia/node-downloader-helper#45] opened 2021-03-10 12:30 UTC
Add a option to allow keep the promise from the start when downloading paused and resume.

**Comment by Chaphasilor** [comment] 2021-03-10 14:20
@semdy you mean that the promise from `dh.start()` doesn't resolve/reject until the download is completely finished?

**Comment by semdy** [comment] 2021-03-11 03:41
@Chaphasilor yeah!

**Comment by hgouveia** [comment] 2021-03-11 08:14
Hello @Chaphasilor @semdy  , this is like this by design, the start will resolve when i finishes or failed, pause/resume means the download is still in process just paused, i dont know why it should be resolved when paused, if you can explain you case to better understand 

if you need to achieved this, you could you create your own promise by using the events

**Comment by Chaphasilor** [comment] 2021-03-11 08:27
@hgouveia I believe what @semdy is talking about is that in his case the promise *does* resolve on pause, but he wants it to only resolve if the download is finished, which is exactly what you described how it *should* be.

So I believe this is a bug?

Can you confirm @semdy, does your promise *resolve* on pause, or does it not?

**Comment by semdy** [comment] 2021-03-11 08:30
@Chaphasilor resolve on pause, but i hope it does not.

**Comment by Chaphasilor** [comment] 2021-03-11 08:33
> @Chaphasilor resolve on pause, but i hope it does not.

great, I thought so.

Could please share the a code example? :)

**Comment by semdy** [comment] 2021-03-11 08:47
`
function execQueuePromise(promises) {
  return new Promise((resolve, reject) => {
    ;(async () => {
      try {
        for (let i = 0; i < promises.length; i++) {
          await promises[i]()
        }
        resolve()
      } catch (e) {
        reject(e)
      }
    })()
  })
}

async function downloadFile(fileUrl, savePath) {
  const dh = new DownloaderHelper(fileUrl, savePath)
  return dh.start()
}

function batchDownloadItem(source, savePath) {
  return new Promise((resolve, reject) => {
    ;(async () => {
      const dh = downloadFile(source, savePath)
      dh.then(resolve, reject)
    })()
  })
}

async function batchDownloadFile(fileList, savePath) {
    const downloads = fileList.map(source => () => batchDownloadItem(source, savePath))
    return execQueuePromise(downloads)
}

batchDownloadFile(['http://xxxx', 'http://xxxx'])
`

**Comment by hgouveia** [comment] 2021-03-11 08:56
got it now , thanks @Chaphasilor  and @semdy ,  yes this should not resolve on pause, i will check this

**Comment by semdy** [comment] 2021-03-11 09:02
@hgouveia would you take a look at this issue #44

**Comment by hgouveia** [comment] 2021-03-11 09:11
> @hgouveia would you take a look at this issue #44

yeap i will check both as soon i have the time, but i can promise a day, they are also little bit related, so dont worry i will check both

**Comment by semdy** [comment] 2021-03-11 11:48
@hgouveia It will pretty good if progress throttle time can be customed through options.

**Comment by hgouveia** [comment] 2021-03-11 14:25
> @hgouveia It will pretty good if progress throttle time can be customed through options.

you could achieve this using the `progress` one , since will be emitted as soon the data comes, so you can do there your own logic, like update the progress every 1 sec or as you wish

**Comment by hgouveia** [comment] 2021-04-09 14:18
Closing, fixed in new version `1.0.18`
https://github.com/hgouveia/node-downloader-helper/releases/tag/v1.0.18

**Closed by hgouveia** 2021-04-09 14:18 UTC
Labels: bug
